#!/bin/bash

. /data/config
input_dir=$1
out_dir=$2
prefix=$3
file_name=$(cd /data/$input_dir && ls *)

echo "Rooting the tree with Fastroot"
mkdir -p /data/$prefix"1-FastRoot_tree_rooting"
if [ $fastroot_rooting_method == "og" ] || [ $fastroot_rooting_method == "OG" ]; then
	docker run --rm -v $dir:/data pegi3s/fastroot -i /data/$input_dir/$file_name -m $fastroot_rooting_method -g "$fastroot_outgroup" -o /data/$prefix"1-FastRoot_tree_rooting"/$file_name"_rooted.nwk" > /dev/null 2>&1
else
	docker run --rm -v $dir:/data pegi3s/fastroot -i /data/$input_dir/$file_name -m $fastroot_rooting_method -o /data/$prefix"1-FastRoot_tree_rooting"/$file_name"_rooted.nwk" > /dev/null 2>&1
fi
mkdir -p  /data/$out_dir
cp /data/$prefix"1-FastRoot_tree_rooting"/*_rooted.nwk /data/$out_dir

