#!/bin/bash

. /data/config
input_dir=$1
out_dir=$2
prefix=$3
start=$(echo "docker run --rm  -v $dir:/data pegi3s/$SEDA /opt/SEDA/run-cli.sh")

mkdir -p /data/$prefix"1-Phyloselected" /data/$out_dir
echo "Getting sequences from phylogeny"
docker run --rm -v $dir:/data pegi3s/utilities get_phylo_taxa $get_phylo_taxa_name1 $get_phylo_taxa_name2 /data/$input_dir/*.nuc_aligned /data/$input_dir/*.nwk > /dev/null 2>&1
mv /data/$input_dir/*.excluding /data/$prefix"1-Phyloselected" > /dev/null 2>&1
mv /data/$input_dir/*.only /data/$prefix"1-Phyloselected" > /dev/null 2>&1
$start undo-alignment -id /data/$prefix"1-Phyloselected" -od /data/$prefix"1-Phyloselected" > /dev/null 2>&1
cp /data/$prefix"1-Phyloselected"/*.only /data/$out_dir > /dev/null 2>&1
