#!/bin/bash

. /data/config
input_dir=$1
out_dir=$2
prefix=$3

start=$(echo "docker run --rm  -v $dir:/data pegi3s/$SEDA /opt/SEDA/run-cli.sh")

mkdir -p /data/$prefix"1-merge_files"
echo "Merging files"
$start merge -id /data/$input_dir -od /data/$prefix"1-merge_files" -n "merge_output" -rlb -lb unix -sc "original"
mkdir -p /data/$out_dir /data/$prefix"2-redundant_sequences"
echo "Removing redundant sequences"
$start remove-redundant -id /data/$prefix"1-merge_files" -od /data/$out_dir -rs -smh /data/$prefix"2-redundant_sequences"





