; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                                         = 10210527-x86_64 Linux                      
[ DataSettings ]
datatype                                    = snNucleotide                               
containsCodingNuc                           = False                                      
MissingBaseSymbol                           = ?                                          
IdenticalBaseSymbol                         = .                                          
GapSymbol                                   = -                                          
Labelled Sites                              = All Sites                                  
Labels to Include                           =                                            
[ ProcessTypes ]
ppInfer                                     = true                                       
ppMP                                        = true                                       
[ AnalysisSettings ]
Analysis                                    = Phylogeny Reconstruction                   
Statistical Method                          = Maximum Parsimony                          
Phylogeny Test                              = ====================                       
Test of Phylogeny                           = Bootstrap method                                       
No. of Bootstrap Replications               = #bootstrap#                             
Substitution Model                          = ====================                       
Substitutions Type                          = Nucleotide                                 
Data Subset to Use                          = ====================                       
Gaps/Missing Data Treatment                 = #treatment#                              
Site Coverage Cutoff (%)                    = 95                             
Tree Inference Options                      = ====================                       
MP Search Method                            = Subtree-Pruning-Regrafting (SPR)           
No. of Initial Trees (random addition)      = 10                                         
MP Search level                             = 1                                          
Max No. of Trees to Retain                  = 100                                        
System Resource Usage                       = ====================                       
Number of Threads                           = 1                                          
Has Time Limit                              = False                                      
Maximum Execution Time                      = -1                                         
