; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                                = 10210527-x86_64 Linux             
[ DataSettings ]
datatype                           = snNucleotide                      
containsCodingNuc                  = False                             
MissingBaseSymbol                  = ?                                 
IdenticalBaseSymbol                = .                                 
GapSymbol                          = -                                 
Labelled Sites                     = All Sites                         
Labels to Include                  =                                   
[ ProcessTypes ]
ppInfer                            = true                              
ppNJ                               = true                              
[ AnalysisSettings ]
Analysis                           = Phylogeny Reconstruction          
Scope                              = All Selected Taxa                 
Statistical Method                 = Neighbor-joining                  
Phylogeny Test                     = ====================              
Test of Phylogeny                  = Bootstrap method                
No. of Bootstrap Replications      = #bootstrap#                             
Substitution Model                 = ====================              
Substitutions Type                 = Nucleotide                        
Model/Method                       = Maximum Composite Likelihood      
Substitutions to Include           = d: Transitions + Transversions    
Rates and Patterns                 = ====================              
Rates among Sites                  = Uniform Rates                     
Gamma Parameter                    = Not Applicable                    
Pattern among Lineages             = Same (Homogeneous)                
Data Subset to Use                 = ====================              
Gaps/Missing Data Treatment        = #treatment#                 
Site Coverage Cutoff (%)           = 95                    
System Resource Usage              = ====================              
Number of Threads                  = 6                                 
Has Time Limit                     = False                             
Maximum Execution Time             = -1                                
