#!/bin/bash

. /data/config
input_dir=$1
out_dir=$2
prefix=$3
start=$(echo "docker run --rm  -v $dir:/data pegi3s/$SEDA /opt/SEDA/run-cli.sh")
file_name=$(cd /data/$input_dir && ls *)

mkdir -p /data/$prefix"1-PC_Translated_sequences"
docker run --rm -v $dir:/data pegi3s/emboss transeq -sequence /data/$input_dir/$file_name -outseq /data/$prefix"1-PC_Translated_sequences"/$file_name.pep
$start reformat -id /data/$prefix"1-PC_Translated_sequences" -od /data/$prefix"1-PC_Translated_sequences" -rlb
cd /data/$prefix"1-PC_Translated_sequences"
sed -i 's/_1$//g' /data/$prefix"1-PC_Translated_sequences"/$file_name.pep
cd /data

echo "Aligning amino acid sequences with Probcons"
mkdir -p /data/$prefix"2-PC_AA_sequence_alignment"
docker run --rm -v $dir:/data pegi3s/probcons bash -c "probcons /data/$prefix"1-PC_Translated_sequences"/$file_name.pep > /data/$prefix"2-PC_AA_sequence_alignment"/$file_name.pep_aligned" > /dev/null 2>&1
$start reformat -id /data/$prefix"2-PC_AA_sequence_alignment" -od /data/$prefix"2-PC_AA_sequence_alignment" -rlb

echo "Creating a nucleotide alignment using the amino acid alignment as a guide"
mkdir -p /data/$prefix"3-PC_Nuc_sequence_alignment"
docker run --rm -v $dir:/data pegi3s/translatorx translatorx_vLocal.pl -i /data/$input_dir/$file_name -a /data/$prefix"2-PC_AA_sequence_alignment"/$file_name.pep_aligned -o /data/$prefix"3-PC_Nuc_sequence_alignment"/$file_name.nuc_aligned > /dev/null 2>&1
cd /data/$prefix"3-PC_Nuc_sequence_alignment"
mv $file_name.nuc_aligned.nt_ali.fasta $file_name.nuc_aligned
rm $file_name*ali.fasta
cd /data
mkdir -p  /data/$out_dir
cp /data/$prefix"3-PC_Nuc_sequence_alignment"/*.nuc_aligned /data/$out_dir
