#!/bin/bash

. /data/config

input_dir=$1
out_dir=$2
prefix=$3

start=$(echo "docker run --rm  -v $dir:/data pegi3s/$SEDA /opt/SEDA/run-cli.sh")

echo "Removing stop codons"
mkdir -p /data/$prefix"1-Remove_stop_codons" /data/$out_dir
$start remove-stop-codons -id /data/$input_dir -od /data/$prefix"1-Remove_stop_codons" -rlb -lb unix > /dev/null
cp /data/$prefix"1-Remove_stop_codons"/* /data/$out_dir

 









