#!/bin/bash

. /data/config
input_dir=$1
out_dir=$2
prefix=$3
file_name=$(cd /data/$input_dir && ls *)

echo "Aligning sequences with T-coffee"
mkdir -p /data/$prefix"1-T-coffee_sequence_alignment_Clustal"
docker run --rm -v $dir:/data pegi3s/tcoffee t_coffee /data/$input_dir/$file_name -run_name /data/$prefix"1-T-coffee_sequence_alignment_Clustal"/$file_name.aln > /dev/null 2>&1
echo "Converting to FASTA"
mkdir -p /data/$prefix"2-T-coffee_FASTA_Conversion"
touch /data/$prefix"2-T-coffee_FASTA_Conversion"/$file_name.aligned
docker run --rm -v $dir:/data pegi3s/tcoffee t_coffee -other_pg seq_reformat -in /data/$prefix"1-T-coffee_sequence_alignment_Clustal"/$file_name.aln -output fasta > /data/$prefix"2-T-coffee_FASTA_Conversion"/$file_name.aligned > /dev/null 2>&1
mkdir -p  /data/$out_dir
cp /data/$prefix"2-T-coffee_FASTA_Conversion"/*.aligned /data/$out_dir


