#!/bin/bash

tcoffee_codons_autop_version=3.0.1
tcoffee_codons_docker_version=12.0.7
tcoffee_codons_program_version=12.0.7
tcoffee_codons_emboss_docker_version=6.6.0
tcoffee_codons_emboss_program_version=6.6.0
tcoffee_codons_translatorx_docker_version=01.09.2022
tcoffee_codons_translatorx_program_version="https://translatorx.org"
tcoffee_ref="Notredame, C., Higgins, D. G., & Heringa, J. (2000)"
tcoffee_doi="10.1006/jmbi.2000.4042"
emboss_ref="Rice, P., Longden, I., & Bleasby, A. (2000)"
emboss_doi="10.1016/s0168-9525(00)02024-2"
translatorx_ref="Abascal, F., Zardoya, R., & Telford, M. J. (2010)"
translatorx_doi="10.1093/nar/gkq291"

. /data/config

input_dir=$1
out_dir=$2
prefix=$3

if [ "$tcoffee_codons_docker_c_version" != "" ]; then
	tcoffee_codons_autop_version="?"
	tcoffee_codons_docker_version=$tcoffee_codons_docker_c_version
	tcoffee_codons_program_version="?"
	tcoffee_ref="?"
	tcoffee_doi="?"
fi

if [ "$tcoffee_codons_emboss_docker_c_version" != "" ]; then
	tcoffee_codons_autop_version="?"
	tcoffee_codons_emboss_docker_version=$tcoffee_codons_emboss_docker_c_version
	tcoffee_codons_emboss_program_version="?"
	emboss_ref="?"
	emboss_doi="?"
fi

if [ "$tcoffee_codons_translatorx_docker_c_version" != "" ]; then
	tcoffee_codons_autop_version="?"
	tcoffee_codons_translatorx_docker_version=$tcoffee_codons_translatorx_docker_c_version
	tcoffee_codons_translatorx_program_version="?"
	translatorx_ref="?"
	translatorx_doi="?"
fi

file_name=$(cd /data/$input_dir && ls *)

mkdir -p /data/$prefix"1-T-coffee_AA_Translated_sequences"
docker run --rm -v $dir:/data pegi3s/emboss:$tcoffee_codons_emboss_docker_version transeq -sequence /data/$input_dir/$file_name -outseq /data/$prefix"1-T-coffee_AA_Translated_sequences"/$file_name.pep > /dev/null 2>&1
cd /data/$prefix"1-T-coffee_AA_Translated_sequences"
sed -i 's/_1$//g' /data/$prefix"1-T-coffee_AA_Translated_sequences"/$file_name.pep
cd /data

echo "Aligning amino acid sequences with T-coffee"
mkdir -p /data/$prefix"2-T-coffee_AA_AA_sequence_alignment_Clustal"
docker run --rm -v $dir:/data pegi3s/tcoffee:$tcoffee_codons_docker_version t_coffee /data/$prefix"1-T-coffee_AA_Translated_sequences"/$file_name.pep -run_name /data/$prefix"2-T-coffee_AA_AA_sequence_alignment_Clustal"/$file_name.aln  > /dev/null 2>&1

echo "Converting to FASTA"
mkdir -p /data/$prefix"3-T-coffee_AA_convert_to_FASTA"
touch /data/$prefix"3-T-coffee_AA_convert_to_FASTA"/$file_name.pep_aligned
docker run --rm -v $dir:/data pegi3s/tcoffee:$tcoffee_codons_docker_version t_coffee -other_pg seq_reformat -in /data/$prefix"2-T-coffee_AA_AA_sequence_alignment_Clustal"/$file_name.aln -output fasta > /data/$prefix"3-T-coffee_AA_convert_to_FASTA"/$file_name.pep_aligned

echo "Creating a nucleotide alignment using the amino acid alignment as a guide"
mkdir -p /data/$prefix"4-T-coffee_AA_Nuc_sequence_alignment"
docker run --rm -v $dir:/data pegi3s/translatorx:$tcoffee_codons_translatorx_docker_version translatorx_vLocal.pl -i /data/$input_dir/$file_name -a /data/$prefix"3-T-coffee_AA_convert_to_FASTA"/$file_name.pep_aligned -o /data/$prefix"4-T-coffee_AA_Nuc_sequence_alignment"/$file_name.nuc_aligned > /dev/null 2>&1
cd /data/$prefix"4-T-coffee_AA_Nuc_sequence_alignment"
mv $file_name.nuc_aligned.nt_ali.fasta $file_name.nuc_aligned
rm $file_name*ali.fasta
cd /data
mkdir -p  /data/$out_dir
cp /data/$prefix"4-T-coffee_AA_Nuc_sequence_alignment"/*.nuc_aligned /data/$out_dir

versions_file="/data/files_to_keep/versions.csv"

if ! grep -qE "^\s*T-coffee_codons" "$versions_file"; then
    echo "T-coffee_codons $tcoffee_codons_autop_version,pegi3s/tcoffee:$tcoffee_codons_docker_version,T-coffee $tcoffee_codons_program_version,\"$tcoffee_ref\",\"$tcoffee_doi\"" >> "$versions_file"
    echo ",pegi3s/emboss:$tcoffee_codons_emboss_docker_version,EMBOSS $tcoffee_codons_emboss_program_version,\"$emboss_ref\",\"$emboss_doi\"" >> "$versions_file"
    echo ",pegi3s/translatorx ($tcoffee_codons_translatorx_docker_version),Translator X ($tcoffee_codons_translatorx_program_version),\"$translatorx_ref\",\"$translatorx_doi\"" >> "$versions_file"
fi

echo -e "tcoffee_ref=\"$tcoffee_ref\"\ntcoffee_doi=\"$tcoffee_doi\"" >> /data/$project/intermediate_files/refs/tmp_references
echo -e "emboss_ref=\"$emboss_ref\"\nemboss_doi=\"$emboss_doi\"" >> /data/$project/intermediate_files/refs/tmp_references
echo -e "translatorx_ref=\"$translatorx_ref\"\ntranslatorx_doi=\"$translatorx_doi\"" >> /data/$project/intermediate_files/refs/tmp_references
