#!/bin/bash

data_summary_autop_version=3.0.1
data_summary_seda_docker_version=1.7.5-docker29.0.1
data_summary_seda_program_version=1.7.5
seda_ref="Lopez-Fernandez, H., Duque, P., Vazquez, N., Fdez-Riverola, F., Reboiro-Jato, M., Vieira, C. P., & Vieira, J. (2022)"
seda_doi="10.1109/TCBB.2020.3040383"

. /data/config

input_dir=$1
out_dir=$2
prefix=$3

if [ "$data_summary_seda_docker_c_version" != "" ]; then
	data_summary_autop_version="?"
	data_summary_seda_docker_version=$data_summary_seda_docker_c_version
	data_summary_seda_program_version="?"
	seda_ref="?"
	seda_doi="?"

fi

start=$(echo "docker run --rm  -v $dir:/data pegi3s/seda:$data_summary_seda_docker_version /opt/SEDA/run-cli.sh")

echo "Data summary"
mkdir -p /data/$prefix"1-Data_summary"/tmp /data/$out_dir/tmp
taxonomy_header_1=$(echo $data_summary_taxonomy | sed "s/ / \-itf /g")
cd /data/$input_dir
for f in *; do
	mv $f /data/$prefix"1-Data_summary"/tmp
	$start rename-ncbi -id /data/$prefix"1-Data_summary"/tmp -od /data/$out_dir/tmp -fp override -nd '#' -itf $taxonomy_header_1 > /dev/null 2>&1
	mv /data/$prefix"1-Data_summary"/tmp/$f /data/$input_dir
	s=$(shuf -i 1-3 -n 1)
	sleep $s
done
rm -r /data/$prefix"1-Data_summary"/tmp
cd /data/$out_dir/tmp
ls * > list
cut -f2- -d'#' list | sort | uniq -c | tr -s ' ' | sed 's/^ //g' | sort -k2 | sed 's/#/ /g' > counts
sed 's/#/\t/g' list | sort > species_list
cp counts  /data/$out_dir/
cp species_list  /data/$out_dir/
cd /data/$out_dir
rm -r tmp
cp  /data/$out_dir/* /data/$prefix"1-Data_summary"
versions_file="/data/files_to_keep/versions.csv"

if ! grep -qE "^\s*data_summary" "$versions_file"; then
    echo "data_summary $data_summary_autop_version,pegi3s/seda:$data_summary_seda_docker_version,SEDA $data_summary_seda_program_version,\"$seda_ref\",\"$seda_doi\"" >> "$versions_file"
fi
echo -e "seda_ref=\"$seda_ref\"\nseda_doi=\"$seda_doi\"" >> /data/$project/intermediate_files/refs/tmp_references

