#!/bin/bash

phipack_autop_version=3.0.0
phipack_docker_version=1.0.0
phipack_program_version=
phipack_ref="Bruen, T. C., Philippe, H., & Bryant, D. (2006)"
phipack_doi="10.1534/genetics.105.048975"

. /data/config
input_dir=$1
out_dir=$2
prefix=$3
file_name=$(cd /data/$input_dir && ls *)

if [ "$phipack_docker_c_version" != "" ]; then
	phipack_autop_version="?"
	phipack_docker_version=$phipack_docker_c_version
	phipack_program_version="?"
	phipack_ref="?"
	phipack_doi="?"
fi

echo "Executing Phipack"
mkdir -p /data/$out_dir

docker run --rm -v $dir:/data pegi3s/phipack:"$phipack_docker_version" bash -c "Phi -f "/data/$input_dir/*" -p $phipack_permutations -o > "/data/$out_dir/phipack_output""

versions_file="/data/files_to_keep/versions.csv"

if ! grep -qE "^\s*phipack" "$versions_file"; then
    echo "phipack $phipack_autop_version,pegi3s/phipack:$phipack_docker_version,PhiPack $phipack_program_version,\"$phipack_ref\",\"$phipack_doi\"" >> "$versions_file"
fi

echo -e "phipack_ref=\"$phipack_ref\"\nphipack_doi=\"$phipack_doi\"" >> /data/$project/intermediate_files/refs/tmp_references
